inherit_from: .rubocop_todo.yml


# Should remove when this issue has been resolved:
# https://github.com/bbatsov/rubocop/issues/1544
Lint/ShadowingOuterLocalVariable:
  Enabled: false



#---------------------------
# Style configuration
#---------------------------

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  AllowForAlignment: true

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: true

# I think that these are fine if used carefully
Style/MultilineBlockChain:
  Enabled: false


# I think this one is broken...
Style/FileName:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Performance/HashEachMethods:
  AutoCorrect: true

#---------------------------
# Don't intend to fix these:
#---------------------------

# Cop supports --auto-correct.
# Reason: Double spaces can be useful for grouping code
Layout/EmptyLines:
  Enabled: false

# Cop supports --auto-correct.
# Reason: I have very big opinions on this one.  See:
#   https://github.com/bbatsov/ruby-style-guide/issues/329
#   https://github.com/bbatsov/ruby-style-guide/pull/325
Style/NegatedIf:
  Enabled: false

# Cop supports --auto-correct.
# Reason: I'm fine either way on this, but could maybe be convinced that this should be enforced
Style/Not:
  Enabled: false

# Cop supports --auto-correct.
# Reason: I'm fine with this
Style/PerlBackrefs:
  Enabled: false

# Configuration parameters: Methods.
# Reason: We should be able to specify full variable names, even if it's only one line
Style/SingleLineBlockParams:
  Enabled: false

# Offense count: 1
# Reason: Switched `extend self` to `module_function` in id_property.rb but that caused errors
Style/ModuleFunction:
  Enabled: false

# Configuration parameters: AllowSafeAssignment.
# Reason: I'm a proud user of assignment in conditionals.
Lint/AssignmentInCondition:
  Enabled: false

# Reason: I'm proud to be part of the double negative Ruby tradition
Style/DoubleNegation:
  Enabled: false

